const items = [
    { id: 1, word: "apple", emoji: "", isOn: false },
    { id: 2, word: "banana", emoji: "", isOn: false },
    { id: 3, word: "car", emoji: "", isOn: false },
    { id: 4, word: "dog", emoji: "", isOn: false },
    { id: 5, word: "elephant", emoji: "", isOn: false },
    { id: 6, word: "frog", emoji: "", isOn: false },
    { id: 7, word: "grape", emoji: "", isOn: false },
    { id: 8, word: "hat", emoji: "", isOn: false },
    { id: 9, word: "ice cream", emoji: "", isOn: false },
    { id: 10, word: "juice", emoji: "", isOn: false },
    { id: 11, word: "kite", emoji: "🪁", isOn: false },
    { id: 12, word: "lion", emoji: "", isOn: false },
    { id: 13, word: "monkey", emoji: "", isOn: false },
    { id: 14, word: "nut", emoji: "", isOn: false },
    { id: 15, word: "owl", emoji: "", isOn: false },
    { id: 16, word: "penguin", emoji: "", isOn: false },
    { id: 17, word: "quilt", emoji: "️", isOn: false },
    { id: 18, word: "rabbit", emoji: "", isOn: false },
    { id: 19, word: "sun", emoji: "☀️", isOn: false },
    { id: 20, word: "turtle", emoji: "", isOn: false },
    { id: 21, word: "umbrella", emoji: "☂️", isOn: false },
    { id: 22, word: "violin", emoji: "", isOn: false },
    { id: 23, word: "whale", emoji: "", isOn: false },
    { id: 24, word: "xylophone", emoji: "", isOn: false },
    { id: 25, word: "yogurt", emoji: "", isOn: false },
    { id: 26, word: "zebra", emoji: "", isOn: false },
  ];
  
  export default items;