export default [
  { id: 1, word: "apple", emoji: "🍎", isOn: true },
  { id: 2, word: "banana", emoji: "🍌", isOn: true },
  { id: 3, word: "car", emoji: "🚗", isOn: true },
  { id: 4, word: "dog", emoji: "🐕", isOn: true },
  { id: 5, word: "elephant", emoji: "🐘", isOn: true },
  { id: 6, word: "frog", emoji: "🐸", isOn: true },
  { id: 7, word: "grape", emoji: "🍇", isOn: true },
  { id: 8, word: "hat", emoji: "🎩", isOn: true },
  { id: 9, word: "ice cream", emoji: "🍦", isOn :true },
  { id: 10, word: "juice", emoji: "🧃", isOn: true },
  { id: 11, word: "kite", emoji: "🪁", isOn: true },
  { id: 12, word: "lion", emoji: "🦁", isOn: true },
  { id: 13, word: "monkey", emoji: "🐒", isOn: true },
  { id: 14, word: "nut", emoji: "🥜", isOn: true },
  { id: 15, word: "owl", emoji: "🦉", isOn: true },
  { id: 16, word: "penguin", emoji: "🐧", isOn: true },
  { id: 17, word: "quilt", emoji: "🛏️", isOn: true },
  { id: 18, word: "rabbit", emoji: "🐇", isOn: true },
  { id: 19, word: "sun", emoji: "☀️", isOn: true },
  { id: 20, word: "turtle", emoji: "🐢", isOn: true },
  { id: 21, word: "umbrella", emoji: "☂️", isOn: true },
  { id: 22, word: "violin", emoji: "🎻", isOn: true },
  { id: 23, word: "whale", emoji: "🐋", isOn: true },
  { id: 24, word: "xylophone", emoji: "🎵", isOn: true },
  { id: 25, word: "yogurt", emoji: "🍦", isOn: true },
  { id: 26, word: "zebra", emoji: "🦓", isOn: true },
];
