const items = [
  { id: 1, word: "apple", emoji: "🍎" },
  { id: 2, word: "banana", emoji: "🍌" },
  { id: 3, word: "car", emoji: "🚗" },
  { id: 4, word: "dog", emoji: "🐕" },
  { id: 5, word: "elephant", emoji: "🐘" },
  { id: 6, word: "frog", emoji: "🐸" },
  { id: 7, word: "grape", emoji: "🍇" },
  { id: 8, word: "hat", emoji: "🎩" },
  { id: 9, word: "ice cream", emoji: "🍦" },
  { id: 10, word: "juice", emoji: "🧃" },
  { id: 11, word: "kite", emoji: "🪁" },
  { id: 12, word: "lion", emoji: "🦁" },
  { id: 13, word: "monkey", emoji: "🐒" },
  { id: 14, word: "nut", emoji: "🥜" },
  { id: 15, word: "owl", emoji: "🦉" },
  { id: 16, word: "penguin", emoji: "🐧" },
  { id: 17, word: "quilt", emoji: "🛏️" },
  { id: 18, word: "rabbit", emoji: "🐇" },
  { id: 19, word: "sun", emoji: "☀️" },
  { id: 20, word: "turtle", emoji: "🐢" },
  { id: 21, word: "umbrella", emoji: "☂️" },
  { id: 22, word: "violin", emoji: "🎻" },
  { id: 23, word: "whale", emoji: "🐋" },
  { id: 24, word: "xylophone", emoji: "🎵" },
  { id: 25, word: "yogurt", emoji: "🍦" },
  { id: 26, word: "zebra", emoji: "🦓" },
];

export default items;